echo ""
echo "Column 1 background = ${column1_background:-default} ($(name_color "$column1_background"))"
echo "Column 1 font color = ${column1_font_color:-default} ($(name_color "$column1_font_color"))"
echo "Column 2 background = ${column2_background:-default} ($(name_color "$column2_background"))"
echo "Column 2 font color = ${column2_font_color:-default} ($(name_color "$column2_font_color"))"